In [1]:
import sys
sys.path.append('./paralel_planarity_criterion')

import numpy as np
import random, time

import paralel_methods as pm
from SAT2_solver import SAT2_solver

In [2]:
# 🎲 Generate a random seed
seed = random.randint(0, 2**32 - 1)
print("Using seed:", seed)

# 🌱 Seed NumPy’s RNG
np.random.seed(seed)

Using seed: 3558602060


In [3]:
N = 250 # With N=200 GPU is faster. From 257 We get clEnqueueNDRangeKernel failed: INVALID_WORK_GROUP_SIZE
A = np.random.randint(0, 2, size=(N, N)).astype(np.int8)
B = A.T.copy() 

start_cpu = time.perf_counter()
C_paralel = pm.multiply_or_and(A, B)
end_cpu = time.perf_counter()

print("\nMatriz A:")
print(A)
print("\nMatriz B:")
print(B)
print()
print("----------------------------")
print("Paralel GPU implementation")
print(f"GPU OR-AND Time: {(end_cpu - start_cpu)*1000:.2f} ms")
print("Type of C:", type(C_paralel))
print("\nResultado C (OR-AND):")
print(C_paralel)


# --- CPU: Pure Python ---
solver = SAT2_solver()

start_cpu = time.time()
C_sequential = solver.mult_matrix_or_and(A.tolist(), B.tolist())  # Convert np arrays to lists
end_cpu = time.time()

print()
print("--------------------------")
print("Sequential CPU implementation")
print(f"CPU OR-AND Time: {(end_cpu - start_cpu)*1000:.2f} ms")
print("Type of C:", type(C_sequential))
print("\nResultado C (OR-AND):")
print(np.array(C_sequential, dtype=np.int8))


Matriz A:
[[1 1 1 ... 1 1 0]
 [0 1 0 ... 1 1 1]
 [1 1 0 ... 1 1 0]
 ...
 [1 1 1 ... 1 0 0]
 [1 1 0 ... 1 1 1]
 [1 1 1 ... 1 1 0]]

Matriz B:
[[1 0 1 ... 1 1 1]
 [1 1 1 ... 1 1 1]
 [1 0 0 ... 1 0 1]
 ...
 [1 1 1 ... 1 1 1]
 [1 1 1 ... 0 1 1]
 [0 1 0 ... 0 1 0]]

----------------------------
Paralel GPU implementation
GPU OR-AND Time: 443.14 ms
Type of C: <class 'numpy.ndarray'>

Resultado C (OR-AND):
[[1 1 1 ... 1 1 1]
 [1 1 1 ... 1 1 1]
 [1 1 1 ... 1 1 1]
 ...
 [1 1 1 ... 1 1 1]
 [1 1 1 ... 1 1 1]
 [1 1 1 ... 1 1 1]]

--------------------------
Sequential CPU implementation
CPU OR-AND Time: 992.72 ms
Type of C: <class 'list'>

Resultado C (OR-AND):
[[1 1 1 ... 1 1 1]
 [1 1 1 ... 1 1 1]
 [1 1 1 ... 1 1 1]
 ...
 [1 1 1 ... 1 1 1]
 [1 1 1 ... 1 1 1]
 [1 1 1 ... 1 1 1]]


In [5]:
import numpy as np
import time
from SAT2_solver import SAT2_solver
import pandas as pd

solver = SAT2_solver()

# Parámetros
sizes = list(range(10, 251, 20))  # Tamaños de matriz desde 10 hasta 250 en pasos de 20
repeticiones = 5  # Número de repeticiones por tamaño

# Resultados acumulados
resultados = []

for N in sizes:
    tiempos_gpu = []
    tiempos_cpu = []
    
    for _ in range(repeticiones):
        A = np.random.randint(0, 2, size=(N, N)).astype(np.int8)
        B = A.T.copy()

        # GPU Paralelo (simulado)
        start_gpu = time.perf_counter()
        _ = pm.multiply_or_and(A, B)
        end_gpu = time.perf_counter()
        tiempos_gpu.append((end_gpu - start_gpu) * 1000)

        # CPU Secuencial
        start_cpu = time.perf_counter()
        _ = solver.mult_matrix_or_and(A.tolist(), B.tolist())
        end_cpu = time.perf_counter()
        tiempos_cpu.append((end_cpu - start_cpu) * 1000)

    resultados.append({
        "Tamaño de Matriz": N,
        "Tiempo Promedio GPU (ms)": np.mean(tiempos_gpu),
        "Tiempo Promedio CPU (ms)": np.mean(tiempos_cpu)
    })

# Mostrar resultados como tabla
df = pd.DataFrame(resultados)
print("\n================== RESULTADOS FINALES ==================")
print(df.to_string(index=False))




================== RESULTADOS FINALES ==================
 Tamaño de Matriz  Tiempo Promedio GPU (ms)  Tiempo Promedio CPU (ms)
               10                  23.74556                   0.22970
               30                  24.63880                   2.72590
               50                  24.18608                  10.09286
               70                  25.90630                  25.08000
               90                  27.43838                  55.15986
              110                  31.06080                  98.23894
              130                  34.85616                 156.39568
              150                  39.76218                 231.23026
              170                  53.00996                 363.20562
              190                  63.08996                 461.11724
              210                  70.98028                 605.66044
              230                  82.45220                 770.75622
              250               