In [1]:
import sys
sys.path.append('./paralel_planarity_criterion')

import numpy as np
import random, time

import paralel_methods as pm
from SAT2_solver import SAT2_solver

In [2]:
# 🎲 Generate a random seed
seed = random.randint(0, 2**32 - 1)
print("Using seed:", seed)

# 🌱 Seed NumPy’s RNG
np.random.seed(seed)

Using seed: 3773325877


In [28]:
N = 200 # With N=200 GPU is faster. From 257 We get clEnqueueNDRangeKernel failed: INVALID_WORK_GROUP_SIZE
A = np.random.randint(0, 2, size=(N, N)).astype(np.int8)
B = A.T.copy() 

start_cpu = time.perf_counter()
C_paralel = pm.multiply_or_and(A, B)
end_cpu = time.perf_counter()

print("\nMatriz A:")
print(A)
print("\nMatriz B:")
print(B)
print()
print("----------------------------")
print("Paralel GPU implementation")
print(f"GPU OR-AND Time: {(end_cpu - start_cpu)*1000:.2f} ms")
print("Type of C:", type(C_paralel))
print("\nResultado C (OR-AND):")
print(C_paralel)


# --- CPU: Pure Python ---
solver = SAT2_solver()

start_cpu = time.time()
C_sequential = solver.mult_matrix_or_and(A.tolist(), B.tolist())  # Convert np arrays to lists
end_cpu = time.time()

print()
print("--------------------------")
print("Sequential CPU implementation")
print(f"CPU OR-AND Time: {(end_cpu - start_cpu)*1000:.2f} ms")
print("Type of C:", type(C_sequential))
print("\nResultado C (OR-AND):")
print(np.array(C_sequential, dtype=np.int8))


Matriz A:
[[1 1 1 ... 1 0 0]
 [1 0 0 ... 1 1 0]
 [1 0 0 ... 0 1 1]
 ...
 [1 1 1 ... 1 0 1]
 [1 1 0 ... 0 0 1]
 [1 0 0 ... 1 0 1]]

Matriz B:
[[1 1 1 ... 1 1 1]
 [1 0 0 ... 1 1 0]
 [1 0 0 ... 1 0 0]
 ...
 [1 1 0 ... 1 0 1]
 [0 1 1 ... 0 0 0]
 [0 0 1 ... 1 1 1]]

----------------------------
Paralel GPU implementation
GPU OR-AND Time: 84.99 ms
Type of C: <class 'numpy.ndarray'>

Resultado C (OR-AND):
[[1 1 1 ... 1 1 1]
 [1 1 1 ... 1 1 1]
 [1 1 1 ... 1 1 1]
 ...
 [1 1 1 ... 1 1 1]
 [1 1 1 ... 1 1 1]
 [1 1 1 ... 1 1 1]]

--------------------------
Sequential CPU implementation
CPU OR-AND Time: 531.77 ms
Type of C: <class 'list'>

Resultado C (OR-AND):
[[1 1 1 ... 1 1 1]
 [1 1 1 ... 1 1 1]
 [1 1 1 ... 1 1 1]
 ...
 [1 1 1 ... 1 1 1]
 [1 1 1 ... 1 1 1]
 [1 1 1 ... 1 1 1]]
