In [1]:
import sys
sys.path.append('./paralel_planarity_criterion')

import numpy as np
import random, time

import paralel_methods as pm
from SAT2_solver import SAT2_solver

In [2]:
# 🎲 Generate a random seed
seed = random.randint(0, 2**32 - 1)
print("Using seed:", seed)

# 🌱 Seed NumPy’s RNG
np.random.seed(seed)

Using seed: 24528315


In [11]:
N = 250 # With N=200 GPU is faster. From 257 We get clEnqueueNDRangeKernel failed: INVALID_WORK_GROUP_SIZE
A = np.random.randint(0, 2, size=(N, N)).astype(np.int8)
B = A.T.copy() 

start_cpu = time.perf_counter()
C_paralel = pm.multiply_or_and(A, B)
end_cpu = time.perf_counter()

print("\nMatriz A:")
print(A)
print("\nMatriz B:")
print(B)
print()
print("----------------------------")
print("Paralel GPU implementation")
print(f"GPU OR-AND Time: {(end_cpu - start_cpu)*1000:.2f} ms")
print("Type of C:", type(C_paralel))
print("\nResultado C (OR-AND):")
print(C_paralel)


# --- CPU: Pure Python ---
solver = SAT2_solver()

start_cpu = time.time()
C_sequential = solver.mult_matrix_or_and(A.tolist(), B.tolist())  # Convert np arrays to lists
end_cpu = time.time()

print()
print("--------------------------")
print("Sequential CPU implementation")
print(f"CPU OR-AND Time: {(end_cpu - start_cpu)*1000:.2f} ms")
print("Type of C:", type(C_sequential))
print("\nResultado C (OR-AND):")
print(np.array(C_sequential, dtype=np.int8))


Matriz A:
[[1 1 0 ... 1 1 1]
 [1 1 1 ... 1 1 1]
 [0 1 1 ... 0 0 1]
 ...
 [1 0 1 ... 1 0 1]
 [0 1 1 ... 1 1 1]
 [1 0 0 ... 1 0 0]]

Matriz B:
[[1 1 0 ... 1 0 1]
 [1 1 1 ... 0 1 0]
 [0 1 1 ... 1 1 0]
 ...
 [1 1 0 ... 1 1 1]
 [1 1 0 ... 0 1 0]
 [1 1 1 ... 1 1 0]]

----------------------------
Paralel GPU implementation
GPU OR-AND Time: 13.12 ms
Type of C: <class 'numpy.ndarray'>

Resultado C (OR-AND):
[[1 1 1 ... 1 1 1]
 [1 0 1 ... 1 1 1]
 [1 1 0 ... 1 1 1]
 ...
 [1 1 1 ... 0 1 1]
 [1 1 1 ... 1 0 1]
 [1 1 1 ... 1 1 1]]

--------------------------
Sequential CPU implementation
CPU OR-AND Time: 1020.68 ms
Type of C: <class 'list'>

Resultado C (OR-AND):
[[1 1 1 ... 1 1 1]
 [1 1 1 ... 1 1 1]
 [1 1 1 ... 1 1 1]
 ...
 [1 1 1 ... 1 1 1]
 [1 1 1 ... 1 1 1]
 [1 1 1 ... 1 1 1]]


In [8]:
import numpy as np
import time
from SAT2_solver import SAT2_solver
import pandas as pd

# Simulación de implementación paralela (reemplaza con tu método real de GPU)
class ParallelMatrix:
    def multiply_or_and(self, A, B):
        return (np.dot(A, B) > 0).astype(np.int8)

pm = ParallelMatrix()
solver = SAT2_solver()

# Parámetros
sizes = list(range(10, 251, 20))  # Tamaños de matriz desde 10 hasta 250 en pasos de 20
repeticiones = 5  # Número de repeticiones por tamaño

# Resultados acumulados
resultados = []

for N in sizes:
    tiempos_gpu = []
    tiempos_cpu = []
    
    for _ in range(repeticiones):
        A = np.random.randint(0, 2, size=(N, N)).astype(np.int8)
        B = A.T.copy()

        # GPU Paralelo (simulado)
        start_gpu = time.perf_counter()
        _ = pm.multiply_or_and(A, B)
        end_gpu = time.perf_counter()
        tiempos_gpu.append((end_gpu - start_gpu) * 1000)

        # CPU Secuencial
        start_cpu = time.perf_counter()
        _ = solver.mult_matrix_or_and(A.tolist(), B.tolist())
        end_cpu = time.perf_counter()
        tiempos_cpu.append((end_cpu - start_cpu) * 1000)

    resultados.append({
        "Tamaño de Matriz": N,
        "Tiempo Promedio GPU (ms)": np.mean(tiempos_gpu),
        "Tiempo Promedio CPU (ms)": np.mean(tiempos_cpu)
    })

# Mostrar resultados como tabla
df = pd.DataFrame(resultados)
print("\n================== RESULTADOS FINALES ==================")
print(df.to_string(index=False))




================== RESULTADOS FINALES ==================
 Tamaño de Matriz  Tiempo Promedio GPU (ms)  Tiempo Promedio CPU (ms)
               10                   0.00860                   0.13382
               30                   0.02642                   2.15490
               50                   0.10386                   9.12868
               70                   0.24416                  24.08890
               90                   0.63320                  49.27902
              110                   0.96356                  91.90980
              130                   1.58034                 150.33916
              150                   2.37768                 230.51766
              170                   3.39164                 326.33698
              190                   5.28138                 464.00160
              210                   6.44236                 620.04154
              230                   8.58626                 777.68032
              250               